### ISSUE TITLE
When app. is in background or inactive how am i able to get data from push notification?

### ISSUE THREAD

**Issue by NayanBhut** [ibm-mobile-push/ios#17]
When app. is in foreground i am able to get push notification data from the method of
`MCESdk.shared.presentNotification = {(userInfo) -> Bool in
            return true        
}`
 in swift and
`MCESdk.sharedInstance.presentNotification = ^BOOL(NSDictionary * userInfo){
            return TRUE;
};`
 in Objective C, but how am i able to get data when app. is inactive or background.This methods are not helping me in background or inactive.

**Comment by jbuchman** [comment]
The presentNotification API was added so that your application can decide to present the notification or not by returning true or false. 

We use notification-action and category-actions entries in the push payload or action payloads in inbox and inapp to specify the action associated with an event. 

To handle those actions your application should register with the MCEActionRegistry to handle specific named "type"s of actions.

For instance, your app could register to handle the "sendEmail" action with Swift code like this:
```
let mail = MailDelegate();
MCEActionRegistry.shared.registerTarget(mail, with: #selector(mail.sendEmail(action:)), forAction: "sendEmail")
```
Then the MailDelegate class can define what happens when the sendEmail selector is triggered:
```
class MailDelegate {
    @objc func sendEmail(action: NSDictionary)
    {
          let emailAddress = action["value"] as! String
          ...
    }
```

This action can be triggered via a push action:
```
{ "aps": {"alert": "hello world"}, "notification-action": { "type": "sendEmail", "value": "some email address for instance" }  } 
```

But, it could also be triggered by an InApp message or an Inbox message

**Comment by NayanBhut** [comment]
Thanks your code solves my issue.
